# Generated by Django 4.2.6 on 2023-10-27 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rankingBuku', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='listbook',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='list_book_covers/'),
        ),
    ]
