# Generated by Django 4.2.6 on 2023-10-29 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rankingBuku', '0003_rename_cover_image_listbook_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listbook',
            name='image',
        ),
    ]
