# Generated by Django 4.2.6 on 2023-10-29 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rankingBuku', '0004_remove_listbook_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='listbook',
            name='image',
            field=models.CharField(default='https://i.imgur.com/CFVTM7y.png', max_length=255),
        ),
    ]
