# Generated by Django 4.2.6 on 2023-10-16 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookcollections', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookcollection',
            name='status_baca',
            field=models.CharField(choices=[('C', 'Completed'), ('R', 'Reading'), ('PR', 'Plan to Read'), ('D', 'Dropped')], default='PR', max_length=2),
        ),
    ]
