# Generated by Django 4.2.6 on 2023-10-21 14:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shared_models', '0001_initial'),
        ('bookcollections', '0002_bookcollection_status_baca'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookcollection',
            name='book',
        ),
        migrations.AddField(
            model_name='bookcollection',
            name='book',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='shared_models.book'),
        ),
    ]
