# Generated by Django 4.2.6 on 2023-10-27 16:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bookcollections', '0003_remove_bookcollection_book_bookcollection_book'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookcollection',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
