# Generated by Django 4.2.6 on 2023-10-29 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Log',
        ),
    ]
