# Generated by Django 4.2.6 on 2023-10-27 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forumDiskusi', '0003_bookreview_reviewer_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookreview',
            name='star_rating',
            field=models.PositiveSmallIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=1),
            preserve_default=False,
        ),
    ]
