# Generated by Django 4.2.6 on 2023-10-27 06:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forumDiskusi', '0004_bookreview_star_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookreview',
            name='user',
        ),
    ]
