# Generated by Django 4.2.6 on 2023-10-27 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forumDiskusi', '0005_remove_bookreview_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookreview',
            name='star_rating',
        ),
        migrations.AddField(
            model_name='bookreview',
            name='rating',
            field=models.IntegerField(default=None),
        ),
    ]
