# Generated by Django 4.2.4 on 2023-10-27 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forumDiskusi', '0007_remove_bookreview_rating_bookreview_star_rating'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookreview',
            old_name='created_at',
            new_name='date',
        ),
    ]
