# Generated by Django 4.2.6 on 2023-10-28 09:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('forumDiskusi', '0011_alter_bookreview_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookreview',
            name='star_rating',
            field=models.PositiveSmallIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bookreview',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviewss', to=settings.AUTH_USER_MODEL),
        ),
    ]
